runtime: nodejs22
# ubah sesuai nama dan nim
service: namanim
#contoh:nouvalhabibie2211521020
handlers:
  - url: /.*
    script: auto
    secure: always

automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: 2
  min_pending_latency: 30ms
  max_pending_latency: automatic
  max_concurrent_requests: 50
